# Generated by Django 2.1.5 on 2019-02-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_merge_20190221_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='contract_version',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
